# Generated by Django 5.1.4 on 2024-12-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
    ]
