# Generated by Django 5.1.4 on 2025-01-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitprogress',
            name='streak',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
