# Generated by Django 5.1.4 on 2025-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habitprogress_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitprogress',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
