# Generated by Django 5.1.4 on 2025-01-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_remove_habitprogress_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitprogress',
            name='streak',
        ),
    ]
