# Generated by Django 5.1.4 on 2025-01-13 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habitprogress_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habituser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
    ]
