# Generated by Django 5.1.4 on 2025-01-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habituser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habituser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
